In [77]:
!pip install mysql-connector-python pandas

Requirement already satisfied: mysql-connector-python in c:\users\sadan\anaconda3\lib\site-packages (26.7.0)
Requirement already satisfied: pandas in c:\users\sadan\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\sadan\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\sadan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\sadan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\sadan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\sadan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [78]:
import mysql.connector
import pandas as pd

In [79]:
import mysql.connector
import pandas as pd

conn = mysql.connector.connect(
    host="localhost",
    port=3306,
    user="root",
    password="betroot",
    database="financial_operations"
)

cursor = conn.cursor()

# Load customers
cursor.execute("SELECT * FROM customers")
customers = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

# Load transactions
cursor.execute("SELECT * FROM transactions")
transactions = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

# Load fraud alerts
cursor.execute("SELECT * FROM fraud_alerts")
fraud_alerts = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

# Load service cases
cursor.execute("SELECT * FROM service_cases")
service_cases = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

print("Customers:", customers.shape)
print("Transactions:", transactions.shape)
print("Fraud Alerts:", fraud_alerts.shape)
print("Service Cases:", service_cases.shape)

Customers: (1186, 9)
Transactions: (6822, 10)
Fraud Alerts: (1084, 8)
Service Cases: (2356, 11)

In [80]:
cursor = conn.cursor()

cursor.execute("SHOW TABLES")

for table in cursor:
    print(table)

('customers',)
('fraud_alerts',)
('service_cases',)
('transactions',)

## 1. Load all four tables

In [81]:
customers.head()
transactions.head()
fraud_alerts.head()
service_cases.head()

,case_id,customer_id,transaction_id,created_at,case_type,priority,status,resolution_time_hours,sla_breached,channel,customer_query
0,CASE000001,CUST00226,TXN0002346,2026-06-21,Card Issue,Low,In Progress,14.08,False,App,My card transaction is not working.
1,CASE000002,CUST00083,TXN0002212,2026-04-28,Transaction Dispute,Medium,Resolved,7.86,False,Chat,I do not recognize this transaction.
2,CASE000003,CUST00214,TXN0006604,2025-10-20,Card Issue,High,Resolved,18.40,False,Email,My card transaction is not working.
3,CASE000004,CUST00577,TXN0003732,2026-01-19,General Enquiry,,Resolved,28.13,True,Email,I need information about my account.
4,CASE000005,CUST00913,TXN0000554,2025-01-15,Refund,High,Resolved,21.36,False,App,When will I receive my refund?

## 2. checking table structure

In [82]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1186 entries, 0 to 1185
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customer_id       1186 non-null   object
 1   full_name         1186 non-null   object
 2   age               1186 non-null   int64
 3   gender            1186 non-null   object
 4   city              1186 non-null   object
 5   account_type      1186 non-null   object
 6   customer_segment  1186 non-null   object
 7   kyc_status        1186 non-null   object
 8   onboarding_date   1186 non-null   object
dtypes: int64(1), object(8)
memory usage: 83.5+ KB

In [83]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6822 entries, 0 to 6821
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   transaction_id         6822 non-null   object
 1   customer_id            6822 non-null   object
 2   transaction_timestamp  6822 non-null   datetime64[ns]
 3   transaction_type       6822 non-null   object
 4   amount                 6822 non-null   object
 5   merchant_category      6822 non-null   object
 6   payment_channel        6822 non-null   object
 7   transaction_status     6822 non-null   object
 8   is_international       6822 non-null   int64
 9   failed_attempts        6822 non-null   int64
dtypes: datetime64[ns](1), int64(2), object(7)
memory usage: 533.1+ KB

In [84]:
fraud_alerts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1084 entries, 0 to 1083
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   alert_id              1084 non-null   object
 1   transaction_id        1084 non-null   object
 2   alert_timestamp       1084 non-null   datetime64[ns]
 3   anomaly_score         1084 non-null   object
 4   alert_type            1084 non-null   object
 5   risk_level            1084 non-null   object
 6   investigation_status  1084 non-null   object
 7   analyst_action        1084 non-null   object
dtypes: datetime64[ns](1), object(7)
memory usage: 67.9+ KB

In [85]:
service_cases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2356 entries, 0 to 2355
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   case_id                2356 non-null   object
 1   customer_id            2356 non-null   object
 2   transaction_id         2356 non-null   object
 3   created_at             2356 non-null   object
 4   case_type              2356 non-null   object
 5   priority               2356 non-null   object
 6   status                 2356 non-null   object
 7   resolution_time_hours  2356 non-null   object
 8   sla_breached           2356 non-null   object
 9   channel                2356 non-null   object
 10  customer_query         2356 non-null   object
dtypes: object(11)
memory usage: 202.6+ KB

## 3. Checking missing values

In [86]:
print("CUSTOMERS")
print(customers.isnull().sum())

CUSTOMERS
customer_id         0
full_name           0
age                 0
gender              0
city                0
account_type        0
customer_segment    0
kyc_status          0
onboarding_date     0
dtype: int64

In [87]:
print("\nTRANSACTIONS")
print(transactions.isnull().sum())

TRANSACTIONS
transaction_id           0
customer_id              0
transaction_timestamp    0
transaction_type         0
amount                   0
merchant_category        0
payment_channel          0
transaction_status       0
is_international         0
failed_attempts          0
dtype: int64

In [88]:
print("\nFRAUD ALERTS")
print(fraud_alerts.isnull().sum())

FRAUD ALERTS
alert_id                0
transaction_id          0
alert_timestamp         0
anomaly_score           0
alert_type              0
risk_level              0
investigation_status    0
analyst_action          0
dtype: int64

In [89]:
print("\nSERVICE CASES")
print(service_cases.isnull().sum())

SERVICE CASES
case_id                  0
customer_id              0
transaction_id           0
created_at               0
case_type                0
priority                 0
status                   0
resolution_time_hours    0
sla_breached             0
channel                  0
customer_query           0
dtype: int64

## 4. Check duplicate primary keys

In [90]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [91]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

In [92]:
fraud_alerts["alert_id"].duplicated().sum()

np.int64(0)

In [93]:
service_cases["case_id"].duplicated().sum()

np.int64(0)

## 5.Check invalid customer data

In [94]:
customers[
    (customers["age"] < 18) |
    (customers["age"] > 100)
]

Empty DataFrame
Columns: [customer_id, full_name, age, gender, city, account_type, customer_segment, kyc_status, onboarding_date]
Index: []

In [95]:
customers["kyc_status"].value_counts(dropna=False)

kyc_status
Verified    995
Pending     117
Expired      56
             18
Name: count, dtype: int64

In [96]:
customers["account_type"].value_counts(dropna=False)

account_type
Savings    1002
Current     184
Name: count, dtype: int64

In [97]:
customers["customer_segment"].value_counts(dropna=False)

customer_segment
Retail       743
Premium      241
SME          159
Corporate     43
Name: count, dtype: int64

## 6.Validate transaction data

In [98]:
transactions["amount"].describe()

count      6822
unique     6725
top       50.00
freq         15
Name: amount, dtype: object

In [99]:
transactions["transaction_id"].duplicated().sum()

np.int64(0)

In [100]:
transactions["customer_id"].isnull().sum()

np.int64(0)

## 8. Validate fraud alerts

In [101]:
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
]

In [102]:
len(orphan_fraud)

0

In [103]:
orphan_fraud[
    ["alert_id", "transaction_id"]
]

Empty DataFrame
Columns: [alert_id, transaction_id]
Index: []

In [104]:
transaction_mapping = {
    "ALERT001": "TXN001",
    "ALERT002": "TXN002",
    "ALERT003": "TXN003"
}

In [105]:
cursor = conn.cursor()

for alert_id, transaction_id in transaction_mapping.items():
    cursor.execute(
        """
        UPDATE fraud_alerts
        SET transaction_id = %s
        WHERE alert_id = %s
        """,
        (transaction_id, alert_id)
    )

conn.commit()

print("Fraud alert transaction IDs updated successfully.")

Fraud alert transaction IDs updated successfully.

In [106]:
!pip install sqlalchemy pymysql

Requirement already satisfied: sqlalchemy in c:\users\sadan\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: pymysql in c:\users\sadan\anaconda3\lib\site-packages (1.2.3)
Requirement already satisfied: greenlet>=1 in c:\users\sadan\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\sadan\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)

In [107]:
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:betroot@localhost:3306/financial_operations"
)

In [108]:
import pandas as pd

customers = pd.read_sql("SELECT * FROM customers", engine)
transactions = pd.read_sql("SELECT * FROM transactions", engine)
fraud_alerts = pd.read_sql("SELECT * FROM fraud_alerts", engine)
service_cases = pd.read_sql("SELECT * FROM service_cases", engine)

In [109]:
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
]

print("Orphan fraud records:", len(orphan_fraud))

Orphan fraud records: 0

In [110]:
cursor = conn.cursor()

for alert_id, transaction_id in transaction_mapping.items():
    cursor.execute(
        """
        UPDATE fraud_alerts
        SET transaction_id = %s
        WHERE alert_id = %s
        """,
        (transaction_id, alert_id)
    )

conn.commit()

print("Fraud alert transaction IDs updated successfully.")

Fraud alert transaction IDs updated successfully.

In [111]:
transaction_mapping = {
    "ALRT000133": "TXN0000136",
    "ALRT000139": "TXN0000376",
    "ALRT000141": "TXN0000185",
    "ALRT000239": "TXN0000515",
    "ALRT000240": "TXN0000267",
    "ALRT000247": "TXN0000040",
    "ALRT000259": "TXN0000123",
    "ALRT000260": "TXN0000832",
    "ALRT000282": "TXN0000271",
    "ALRT000288": "TXN0000400",
    "ALRT000295": "TXN0000030",
    "ALRT000304": "TXN0001114",
    "ALRT000309": "TXN0001606",
    "ALRT000342": "TXN0000185",
    "ALRT000386": "TXN0000193",
    "ALRT000392": "TXN0000561",
    "ALRT000440": "TXN0000445",
    "ALRT000491": "TXN0000375",
    "ALRT000493": "TXN0000051",
    "ALRT000574": "TXN0001232",
    "ALRT000594": "TXN0000235",
    "ALRT000617": "TXN0000261",
    "ALRT000626": "TXN0000020",
    "ALRT000669": "TXN0000497",
    "ALRT000808": "TXN0000561",
    "ALRT000841": "TXN0000097",
    "ALRT000845": "TXN0002202",
    "ALRT000914": "TXN0000324",
    "ALRT001001": "TXN0000233",
    "ALRT001002": "TXN0000158",
    "ALRT001007": "TXN0001232",
    "ALRT001030": "TXN0001297"
}

In [112]:
cursor = conn.cursor()

for old_id, new_id in transaction_mapping.items():
    cursor.execute(
        """
        UPDATE fraud_alerts
        SET transaction_id = %s
        WHERE transaction_id = %s
        """,
        (new_id, old_id)
    )

conn.commit()

print("Transaction IDs updated successfully.")

Transaction IDs updated successfully.

In [113]:
fraud_alerts = pd.read_sql(
    "SELECT * FROM fraud_alerts",
    engine
)

In [114]:
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
]

print("Remaining orphan records:", len(orphan_fraud))

Remaining orphan records: 0

In [115]:
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

print(orphan_fraud.to_string(index=False))

Empty DataFrame
Columns: [alert_id, transaction_id, alert_timestamp, anomaly_score, alert_type, risk_level, investigation_status, analyst_action]
Index: []

In [116]:
print("Fraud Alerts columns:")
print(fraud_alerts.columns.tolist())

print("\nTransactions columns:")
print(transactions.columns.tolist())

Fraud Alerts columns:
['alert_id', 'transaction_id', 'alert_timestamp', 'anomaly_score', 'alert_type', 'risk_level', 'investigation_status', 'analyst_action']

Transactions columns:
['transaction_id', 'customer_id', 'transaction_timestamp', 'transaction_type', 'amount', 'merchant_category', 'payment_channel', 'transaction_status', 'is_international', 'failed_attempts']

In [117]:
# Make sure dates are datetime
fraud_alerts["alert_timestamp"] = pd.to_datetime(
    fraud_alerts["alert_timestamp"]
)

transactions["transaction_timestamp"] = pd.to_datetime(
    transactions["transaction_timestamp"]
)

# Get orphan fraud alerts
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

# Find transactions on the same date as each alert
candidates = []

for _, alert in orphan_fraud.iterrows():

    same_day = transactions[
        transactions["transaction_timestamp"].dt.date ==
        alert["alert_timestamp"].date()
    ].copy()

    same_day["alert_id"] = alert["alert_id"]
    same_day["old_transaction_id"] = alert["transaction_id"]

    candidates.append(same_day)

candidates = pd.concat(candidates, ignore_index=True)

print(candidates[
    [
        "alert_id",
        "old_transaction_id",
        "transaction_id",
        "customer_id",
        "transaction_timestamp",
        "amount",
        "transaction_type",
        "merchant_category"
    ]
].to_string(index=False))

ValueError: No objects to concatenate

In [118]:
import pandas as pd

# Convert dates
fraud_alerts["alert_timestamp"] = pd.to_datetime(
    fraud_alerts["alert_timestamp"]
)

transactions["transaction_timestamp"] = pd.to_datetime(
    transactions["transaction_timestamp"]
)

# Get orphan alerts
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

print("Orphan alerts:", len(orphan_fraud))

Orphan alerts: 0

In [119]:
candidates = []

for _, alert in orphan_fraud.iterrows():

    matches = transactions[
        transactions["transaction_timestamp"].dt.date ==
        alert["alert_timestamp"].date()
    ].copy()

    for _, transaction in matches.iterrows():

        candidates.append({
            "alert_id": alert["alert_id"],
            "old_transaction_id": alert["transaction_id"],
            "new_transaction_id": transaction["transaction_id"],
            "alert_date": alert["alert_timestamp"].date(),
            "transaction_date": transaction["transaction_timestamp"].date()
        })

candidate_df = pd.DataFrame(candidates)

print(candidate_df)

Empty DataFrame
Columns: []
Index: []

In [120]:
transaction_mapping = {
    "ALRT000133": "TXN0000136",
    "ALRT000139": "TXN0000376",
    "ALRT000141": "TXN0000185",
    "ALRT000239": "TXN0000515",
    "ALRT000240": "TXN0000267",
    "ALRT000247": "TXN0000040",
    "ALRT000259": "TXN0000123",
    "ALRT000260": "TXN0000832",
    "ALRT000282": "TXN0000271",
    "ALRT000288": "TXN0000400",
    "ALRT000295": "TXN0000030",
    "ALRT000304": "TXN0001114",
    "ALRT000309": "TXN0001606",
    "ALRT000342": "TXN0000185",
    "ALRT000386": "TXN0000193",
    "ALRT000392": "TXN0000561",
    "ALRT000440": "TXN0000445",
    "ALRT000491": "TXN0000375",
    "ALRT000493": "TXN0000051",
    "ALRT000574": "TXN0001232",
    "ALRT000594": "TXN0000235",
    "ALRT000617": "TXN0000261",
    "ALRT000626": "TXN0000020",
    "ALRT000669": "TXN0000497",
    "ALRT000808": "TXN0000561",
    "ALRT000841": "TXN0000097",
    "ALRT000845": "TXN0002202",
    "ALRT000914": "TXN0000324",
    "ALRT001001": "TXN0000233",
    "ALRT001002": "TXN0000158",
    "ALRT001007": "TXN0001232",
    "ALRT001030": "TXN0001297"
}

In [121]:
cursor = conn.cursor()

for alert_id, new_transaction_id in transaction_mapping.items():

    cursor.execute(
        """
        UPDATE fraud_alerts
        SET transaction_id = %s
        WHERE alert_id = %s
        """,
        (new_transaction_id, alert_id)
    )

conn.commit()

print("Updated", len(transaction_mapping), "alerts.")

Updated 32 alerts.

In [122]:
fraud_alerts = pd.read_sql(
    "SELECT * FROM fraud_alerts",
    engine
)

orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
]

print("Remaining orphan records:", len(orphan_fraud))

Remaining orphan records: 0

In [123]:
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

print(orphan_fraud[
    ["alert_id", "transaction_id", "alert_timestamp"]
].to_string(index=False))

Empty DataFrame
Columns: [alert_id, transaction_id, alert_timestamp]
Index: []

In [124]:
for _, alert in orphan_fraud.iterrows():

    matches = transactions[
        transactions["transaction_timestamp"].dt.date ==
        alert["alert_timestamp"].date()
    ]

    print("\nAlert:", alert["alert_id"])
    print("Old ID:", alert["transaction_id"])
    print("Date:", alert["alert_timestamp"].date())

    print(
        matches[
            ["transaction_id", "customer_id",
             "transaction_timestamp", "amount"]
        ].to_string(index=False)
    )

In [125]:
# Make sure both date columns are datetime
fraud_alerts["alert_timestamp"] = pd.to_datetime(
    fraud_alerts["alert_timestamp"]
)

transactions["transaction_timestamp"] = pd.to_datetime(
    transactions["transaction_timestamp"]
)

# Get remaining orphan alerts
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

print("Remaining orphan alerts:", len(orphan_fraud))

# Find possible transaction matches
for _, alert in orphan_fraud.iterrows():

    matches = transactions[
        transactions["transaction_timestamp"].dt.date ==
        alert["alert_timestamp"].date()
    ]

    print("\n" + "=" * 70)
    print("Alert ID:", alert["alert_id"])
    print("Old Transaction ID:", alert["transaction_id"])
    print("Alert Date:", alert["alert_timestamp"].date())

    if len(matches) == 0:
        print("NO TRANSACTION FOUND ON THIS DATE")
    else:
        print("\nPossible transactions:")
        print(
            matches[
                [
                    "transaction_id",
                    "customer_id",
                    "transaction_timestamp",
                    "amount",
                    "transaction_type",
                    "merchant_category"
                ]
            ].to_string(index=False)
        )

Remaining orphan alerts: 0

In [126]:

transactions["transaction_timestamp"] = pd.to_datetime(
    transactions["transaction_timestamp"]
)

fraud_alerts["alert_timestamp"] = pd.to_datetime(
    fraud_alerts["alert_timestamp"]
)

# Get remaining orphan alerts
orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
].copy()

# Show transaction fields useful for matching
print(transactions[
    [
        "transaction_id",
        "transaction_timestamp",
        "amount",
        "transaction_type",
        "is_international",
        "failed_attempts"
    ]
].head())

  transaction_id transaction_timestamp   amount transaction_type  \
0     TXN0000001   2025-07-23 22:00:00  1779.86           Credit
1     TXN0000002   2025-01-26 22:00:00   982.17         Transfer
2     TXN0000003   2025-02-24 22:00:00  5741.03            Debit
3     TXN0000004   2026-02-17 14:00:00  3797.44            Debit
4     TXN0000005   2026-01-24 07:00:00   873.60            Debit

   is_international  failed_attempts
0                 0                0
1                 0                0
2                 0                0
3                 0                0
4                 0                1

In [127]:
print(
    transactions[
        ["amount", "is_international", "failed_attempts"]
    ].describe()
)

            amount  is_international  failed_attempts
count   6822.00000       6822.000000      6822.000000
mean    1902.48133          0.057754         0.251686
std     2633.54349          0.233295         0.499942
min        0.00000          0.000000         0.000000
25%      534.51500          0.000000         0.000000
50%     1097.03000          0.000000         0.000000
75%     2239.90000          0.000000         0.000000
max    43312.14000          1.000000         3.000000

In [128]:
fraud_alerts = pd.read_sql("SELECT * FROM fraud_alerts", engine)
transactions = pd.read_sql("SELECT * FROM transactions", engine)

orphan_fraud = fraud_alerts[
    ~fraud_alerts["transaction_id"].isin(
        transactions["transaction_id"]
    )
]

print("Remaining orphan records:", len(orphan_fraud))

Remaining orphan records: 0

In [129]:
customers['city'] = customers['city'].str.strip()

In [130]:
customers['city'] = customers['city'].fillna('Unknown')
customers['kyc_status'] = customers['kyc_status'].fillna('Pending')

In [131]:
transactions = transactions.drop_duplicates()

In [132]:
transactions['transaction_timestamp'] = pd.to_datetime(
    transactions['transaction_timestamp']
)

In [133]:
service_cases['status'] = service_cases['status'].replace({
    'resolved': 'Resolved'
})

In [137]:
import pandas as pd

# Load cleaned data
cursor.execute("SELECT * FROM transactions")
transactions = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

print("========== CLEANED DATA CHECK ==========")

# 1. Number of rows and columns
print("\n1. Dataset Shape:")
print(transactions.shape)


# 2. Check duplicate rows
print("\n2. Duplicate Rows:")
print(transactions.duplicated().sum())


# 3. Check duplicate transaction IDs
print("\n3. Duplicate Transaction IDs:")
print(transactions["transaction_id"].duplicated().sum())


# 4. Check missing values
print("\n4. Missing Values:")
print(transactions.isnull().sum())


# 5. Check missing customer IDs
print("\n5. Missing Customer IDs:")
print(transactions["customer_id"].isnull().sum())


# 6. Check negative amounts
print("\n6. Negative Transaction Amounts:")
print((transactions["amount"] < 0).sum())


# 7. Check payment channel values
print("\n7. Payment Channel Values:")
print(transactions["payment_channel"].value_counts(dropna=False))


# 8. Check transaction status values
print("\n8. Transaction Status Values:")
print(transactions["transaction_status"].value_counts(dropna=False))


# 9. Check invalid transaction timestamps
transactions["transaction_timestamp"] = pd.to_datetime(
    transactions["transaction_timestamp"],
    errors="coerce"
)

print("\n9. Invalid Transaction Timestamps:")
print(transactions["transaction_timestamp"].isnull().sum())


# 10. Check data types
print("\n10. Data Types:")
print(transactions.dtypes)


# 11. Check transaction IDs
print("\n11. Missing Transaction IDs:")
print(transactions["transaction_id"].isnull().sum())


# 12. Check customer ID format
print("\n12. Customer ID Examples:")
print(transactions["customer_id"].head(10))


# 13. Check amount statistics
print("\n13. Amount Statistics:")
print(transactions["amount"].describe())


# 14. Final preview
print("\n14. First 5 Cleaned Records:")
print(transactions.head())


print("\n========== CHECK COMPLETED ==========")

========== CLEANED DATA CHECK ==========

1. Dataset Shape:
(6822, 10)

2. Duplicate Rows:
0

3. Duplicate Transaction IDs:
0

4. Missing Values:
transaction_id           0
customer_id              0
transaction_timestamp    0
transaction_type         0
amount                   0
merchant_category        0
payment_channel          0
transaction_status       0
is_international         0
failed_attempts          0
dtype: int64

5. Missing Customer IDs:
0

6. Negative Transaction Amounts:
0

7. Payment Channel Values:
payment_channel
UPI            2888
Debit Card     1349
Net Banking     925
Credit Card     862
ATM             703
                 80
upi              11
credit_card       2
debit_card        2
Name: count, dtype: int64

8. Transaction Status Values:
transaction_status
Success    5868
Failed      545
Pending     340
             69
Name: count, dtype: int64

9. Invalid Transaction Timestamps:
0

10. Data Types:
transaction_id                   object
customer_id                      object
transaction_timestamp    datetime64[ns]
transaction_type                 object
amount                           object
merchant_category                object
payment_channel                  object
transaction_status               object
is_international                  int64
failed_attempts                   int64
dtype: object

11. Missing Transaction IDs:
0

12. Customer ID Examples:
0    CUST00682
1    CUST01010
2    CUST01002
3    CUST00654
4    CUST00015
5    CUST00261
6    CUST00453
7    CUST00144
8    CUST00968
9    CUST01046
Name: customer_id, dtype: object

13. Amount Statistics:
count      6822
unique     6725
top       50.00
freq         15
Name: amount, dtype: object

14. First 5 Cleaned Records:
  transaction_id customer_id transaction_timestamp transaction_type   amount  \
0     TXN0000001   CUST00682   2025-07-23 22:00:00           Credit  1779.86
1     TXN0000002   CUST01010   2025-01-26 22:00:00         Transfer   982.17
2     TXN0000003   CUST01002   2025-02-24 22:00:00            Debit  5741.03
3     TXN0000004   CUST00654   2026-02-17 14:00:00            Debit  3797.44
4     TXN0000005   CUST00015   2026-01-24 07:00:00            Debit   873.60

  merchant_category payment_channel transaction_status  is_international  \
0     Entertainment     Net Banking             Failed                 0
1     Entertainment     Credit Card            Success                 0
2          Shopping      Debit Card            Success                 0
3              Food      Debit Card             Failed                 0
4              Rent             ATM            Success                 0

   failed_attempts
0                0
1                0
2                0
3                0
4                1

========== CHECK COMPLETED ==========

In [138]:
import pandas as pd

# Load cleaned data
cursor.execute("SELECT * FROM customers")
customers = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

print("========== CLEANED CUSTOMERS DATA CHECK ==========")

# 1. Number of rows and columns
print("\n1. Dataset Shape:")
print(customers.shape)


# 2. Check duplicate rows
print("\n2. Duplicate Rows:")
print(customers.duplicated().sum())


# 3. Check duplicate customer IDs
print("\n3. Duplicate Customer IDs:")
print(customers["customer_id"].duplicated().sum())


# 4. Check missing values
print("\n4. Missing Values:")
print(customers.isnull().sum())


# 5. Check missing customer IDs
print("\n5. Missing Customer IDs:")
print(customers["customer_id"].isnull().sum())


# 6. Check age values
print("\n6. Age Statistics:")
print(customers["age"].describe())


# 7. Check invalid ages
print("\n7. Invalid Ages:")
print(
    customers[
        (customers["age"] < 18) |
        (customers["age"] > 100)
    ][["customer_id", "age"]]
)


# 8. Check gender values
print("\n8. Gender Values:")
print(customers["gender"].value_counts(dropna=False))


# 9. Check account type values
print("\n9. Account Type Values:")
print(customers["account_type"].value_counts(dropna=False))


# 10. Check customer segment values
print("\n10. Customer Segment Values:")
print(customers["customer_segment"].value_counts(dropna=False))


# 11. Check KYC status values
print("\n11. KYC Status Values:")
print(customers["kyc_status"].value_counts(dropna=False))


# 12. Check onboarding date
customers["onboarding_date"] = pd.to_datetime(
    customers["onboarding_date"],
    errors="coerce"
)

print("\n12. Invalid Onboarding Dates:")
print(customers["onboarding_date"].isnull().sum())


# 13. Check customer ID format
print("\n13. Customer ID Examples:")
print(customers["customer_id"].head(10))


# 14. Check city values
print("\n14. City Values:")
print(customers["city"].value_counts(dropna=False).head(20))


# 15. Check data types
print("\n15. Data Types:")
print(customers.dtypes)


# 16. Final preview
print("\n16. First 5 Cleaned Records:")
print(customers.head())


print("\n========== CHECK COMPLETED ==========")

========== CLEANED CUSTOMERS DATA CHECK ==========

1. Dataset Shape:
(1186, 9)

2. Duplicate Rows:
0

3. Duplicate Customer IDs:
0

4. Missing Values:
customer_id         0
full_name           0
age                 0
gender              0
city                0
account_type        0
customer_segment    0
kyc_status          0
onboarding_date     0
dtype: int64

5. Missing Customer IDs:
0

6. Age Statistics:
count    1186.000000
mean       46.158516
std        16.780142
min        18.000000
25%        32.000000
50%        45.000000
75%        61.000000
max        75.000000
Name: age, dtype: float64

7. Invalid Ages:
Empty DataFrame
Columns: [customer_id, age]
Index: []

8. Gender Values:
gender
Male      604
Female    547
Other      35
Name: count, dtype: int64

9. Account Type Values:
account_type
Savings    1002
Current     184
Name: count, dtype: int64

10. Customer Segment Values:
customer_segment
Retail       743
Premium      241
SME          159
Corporate     43
Name: count, dtype: int64

11. KYC Status Values:
kyc_status
Verified    995
Pending     117
Expired      56
             18
Name: count, dtype: int64

12. Invalid Onboarding Dates:
0

13. Customer ID Examples:
0    CUST00001
1    CUST00002
2    CUST00003
3    CUST00004
4    CUST00005
5    CUST00006
6    CUST00007
7    CUST00008
8    CUST00009
9    CUST00010
Name: customer_id, dtype: object

14. City Values:
city
Vijayawada         146
Bengaluru          143
Chennai            140
Delhi              135
Mumbai             124
Visakhapatnam      122
Hyderabad          121
Pune               115
Kolkata            112
                    20
 Hyderabad           3
 Delhi               1
 Kolkata             1
 Chennai             1
 Bengaluru           1
 Visakhapatnam       1
Name: count, dtype: int64

15. Data Types:
customer_id                 object
full_name                   object
age                          int64
gender                      object
city                        object
account_type                object
customer_segment            object
kyc_status                  object
onboarding_date     datetime64[ns]
dtype: object

16. First 5 Cleaned Records:
  customer_id   full_name  age  gender       city account_type  \
0   CUST00001  Customer 1   18    Male  Bengaluru      Current
1   CUST00002  Customer 2   57  Female     Mumbai      Savings
2   CUST00003  Customer 3   52  Female       Pune      Savings
3   CUST00004  Customer 4   21    Male    Kolkata      Savings
4   CUST00005  Customer 5   70  Female  Hyderabad      Savings

  customer_segment kyc_status onboarding_date
0           Retail   Verified      2025-12-09
1           Retail   Verified      2023-11-19
2           Retail   Verified      2026-01-10
3           Retail   Verified      2024-07-28
4           Retail   Verified      2022-01-01

========== CHECK COMPLETED ==========

In [139]:
import pandas as pd

# Load cleaned data
cursor.execute("SELECT * FROM service_cases")
service_cases = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

print("========== CLEANED SERVICE CASES DATA CHECK ==========")

# 1. Number of rows and columns
print("\n1. Dataset Shape:")
print(service_cases.shape)


# 2. Check duplicate rows
print("\n2. Duplicate Rows:")
print(service_cases.duplicated().sum())


# 3. Check duplicate case IDs
print("\n3. Duplicate Case IDs:")
print(service_cases["case_id"].duplicated().sum())


# 4. Check missing values
print("\n4. Missing Values:")
print(service_cases.isnull().sum())


# 5. Check missing customer IDs
print("\n5. Missing Customer IDs:")
print(service_cases["customer_id"].isnull().sum())


# 6. Check missing transaction IDs
print("\n6. Missing Transaction IDs:")
print(service_cases["transaction_id"].isnull().sum())


# 7. Check created_at date
service_cases["created_at"] = pd.to_datetime(
    service_cases["created_at"],
    errors="coerce"
)

print("\n7. Invalid Created Dates:")
print(service_cases["created_at"].isnull().sum())


# 8. Check case type values
print("\n8. Case Type Values:")
print(service_cases["case_type"].value_counts(dropna=False))


# 9. Check priority values
print("\n9. Priority Values:")
print(service_cases["priority"].value_counts(dropna=False))


# 10. Check status values
print("\n10. Status Values:")
print(service_cases["status"].value_counts(dropna=False))


# 11. Check channel values
print("\n11. Channel Values:")
print(service_cases["channel"].value_counts(dropna=False))


# 12. Check resolution time
print("\n12. Resolution Time Statistics:")
print(service_cases["resolution_time_hours"].describe())


# 13. Check negative resolution times
print("\n13. Negative Resolution Times:")
print(
    (
        service_cases["resolution_time_hours"] < 0
    ).sum()
)


# 14. Check SLA breached values
print("\n14. SLA Breached Values:")
print(service_cases["sla_breached"].value_counts(dropna=False))


# 15. Check customer ID format
print("\n15. Customer ID Examples:")
print(service_cases["customer_id"].head(10))


# 16. Check transaction ID format
print("\n16. Transaction ID Examples:")
print(service_cases["transaction_id"].head(10))


# 17. Check data types
print("\n17. Data Types:")
print(service_cases.dtypes)


# 18. Final preview
print("\n18. First 5 Cleaned Records:")
print(service_cases.head())


print("\n========== CHECK COMPLETED ==========")

========== CLEANED SERVICE CASES DATA CHECK ==========

1. Dataset Shape:
(2356, 11)

2. Duplicate Rows:
0

3. Duplicate Case IDs:
0

4. Missing Values:
case_id                  0
customer_id              0
transaction_id           0
created_at               0
case_type                0
priority                 0
status                   0
resolution_time_hours    0
sla_breached             0
channel                  0
customer_query           0
dtype: int64

5. Missing Customer IDs:
0

6. Missing Transaction IDs:
0

7. Invalid Created Dates:
0

8. Case Type Values:
case_type
KYC                    377
Card Issue             346
Refund                 332
General Enquiry        329
Account Issue          327
Payment Failure        324
Transaction Dispute    321
Name: count, dtype: int64

9. Priority Values:
priority
Medium      1151
Low          553
High         513
Critical     104
              35
Name: count, dtype: int64

10. Status Values:
status
Resolved       1225
In Progress     564
Open            399
Escalated       163
resolved          5
Name: count, dtype: int64

11. Channel Values:
channel
Chat      513
Email     480
App       474
Branch    449
Phone     440
Name: count, dtype: int64

12. Resolution Time Statistics:
count     2356
unique    1728
top       9.81
freq         5
Name: resolution_time_hours, dtype: object

13. Negative Resolution Times:
12

14. SLA Breached Values:
sla_breached
False    1726
True      630
Name: count, dtype: int64

15. Customer ID Examples:
0    CUST00226
1    CUST00083
2    CUST00214
3    CUST00577
4    CUST00913
5    CUST01014
6    CUST00568
7    CUST00865
8    CUST00869
9    CUST00767
Name: customer_id, dtype: object

16. Transaction ID Examples:
0    TXN0002346
1    TXN0002212
2    TXN0006604
3    TXN0003732
4    TXN0000554
5    TXN0005113
6    TXN0005977
7    TXN0000337
8    TXN0002746
9    TXN0001758
Name: transaction_id, dtype: object

17. Data Types:
case_id                          object
customer_id                      object
transaction_id                   object
created_at               datetime64[ns]
case_type                        object
priority                         object
status                           object
resolution_time_hours            object
sla_breached                     object
channel                          object
customer_query                   object
dtype: object

18. First 5 Cleaned Records:
      case_id customer_id transaction_id created_at            case_type  \
0  CASE000001   CUST00226     TXN0002346 2026-06-21           Card Issue
1  CASE000002   CUST00083     TXN0002212 2026-04-28  Transaction Dispute
2  CASE000003   CUST00214     TXN0006604 2025-10-20           Card Issue
3  CASE000004   CUST00577     TXN0003732 2026-01-19      General Enquiry
4  CASE000005   CUST00913     TXN0000554 2025-01-15               Refund

  priority       status resolution_time_hours sla_breached channel  \
0      Low  In Progress                 14.08        False     App
1   Medium     Resolved                  7.86        False    Chat
2     High     Resolved                 18.40        False   Email
3              Resolved                 28.13         True   Email
4     High     Resolved                 21.36        False     App

                         customer_query
0   My card transaction is not working.
1  I do not recognize this transaction.
2   My card transaction is not working.
3  I need information about my account.
4        When will I receive my refund?

========== CHECK COMPLETED ==========

In [140]:
import pandas as pd

# Load cleaned data
cursor.execute("SELECT * FROM fraud_alerts")
fraud_alerts = pd.DataFrame(cursor.fetchall(), columns=cursor.column_names)

print("========== CLEANED FRAUD ALERTS DATA CHECK ==========")

# 1. Number of rows and columns
print("\n1. Dataset Shape:")
print(fraud_alerts.shape)


# 2. Check duplicate rows
print("\n2. Duplicate Rows:")
print(fraud_alerts.duplicated().sum())


# 3. Check duplicate alert IDs
print("\n3. Duplicate Alert IDs:")
print(fraud_alerts["alert_id"].duplicated().sum())


# 4. Check missing values
print("\n4. Missing Values:")
print(fraud_alerts.isnull().sum())


# 5. Check missing transaction IDs
print("\n5. Missing Transaction IDs:")
print(fraud_alerts["transaction_id"].isnull().sum())


# 6. Check alert timestamp
fraud_alerts["alert_timestamp"] = pd.to_datetime(
    fraud_alerts["alert_timestamp"],
    errors="coerce"
)

print("\n6. Invalid Alert Timestamps:")
print(fraud_alerts["alert_timestamp"].isnull().sum())


# 7. Check anomaly score
print("\n7. Anomaly Score Statistics:")
print(fraud_alerts["anomaly_score"].describe())


# 8. Check invalid anomaly scores
print("\n8. Invalid Anomaly Scores:")
print(
    fraud_alerts[
        (fraud_alerts["anomaly_score"] < 0) |
        (fraud_alerts["anomaly_score"] > 1)
    ][
        ["alert_id", "transaction_id", "anomaly_score"]
    ]
)


# 9. Check alert type values
print("\n9. Alert Type Values:")
print(fraud_alerts["alert_type"].value_counts(dropna=False))


# 10. Check risk level values
print("\n10. Risk Level Values:")
print(fraud_alerts["risk_level"].value_counts(dropna=False))


# 11. Check investigation status values
print("\n11. Investigation Status Values:")
print(
    fraud_alerts["investigation_status"].value_counts(
        dropna=False
    )
)


# 12. Check analyst action values
print("\n12. Analyst Action Values:")
print(
    fraud_alerts["analyst_action"].value_counts(
        dropna=False
    )
)


# 13. Check transaction ID format
print("\n13. Transaction ID Examples:")
print(fraud_alerts["transaction_id"].head(10))


# 14. Check data types
print("\n14. Data Types:")
print(fraud_alerts.dtypes)


# 15. Final preview
print("\n15. First 5 Cleaned Records:")
print(fraud_alerts.head())


print("\n========== CHECK COMPLETED ==========")

========== CLEANED FRAUD ALERTS DATA CHECK ==========

1. Dataset Shape:
(1084, 8)

2. Duplicate Rows:
0

3. Duplicate Alert IDs:
0

4. Missing Values:
alert_id                0
transaction_id          0
alert_timestamp         0
anomaly_score           0
alert_type              0
risk_level              0
investigation_status    0
analyst_action          0
dtype: int64

5. Missing Transaction IDs:
0

6. Invalid Alert Timestamps:
0

7. Anomaly Score Statistics:
count      1084
unique      607
top       0.389
freq          6
Name: anomaly_score, dtype: object

8. Invalid Anomaly Scores:
Empty DataFrame
Columns: [alert_id, transaction_id, anomaly_score]
Index: []

9. Alert Type Values:
alert_type
Rapid Transactions        230
Unusual Location          227
International Activity    210
High Amount               209
Multiple Failures         208
Name: count, dtype: int64

10. Risk Level Values:
risk_level
Low         460
Medium      362
High        211
Critical     51
Name: count, dtype: int64

11. Investigation Status Values:
investigation_status
Cleared         397
Under Review    334
New             263
Confirmed        78
                 12
Name: count, dtype: int64

12. Analyst Action Values:
analyst_action
Escalate             292
No Action            290
Block Transaction    266
Contact Customer     236
Name: count, dtype: int64

13. Transaction ID Examples:
0    TXN0004029
1    TXN0006211
2    TXN0005346
3    TXN0005366
4    TXN0002162
5    TXN0006218
6    TXN0002081
7    TXN0001610
8    TXN0001334
9    TXN0000666
Name: transaction_id, dtype: object

14. Data Types:
alert_id                        object
transaction_id                  object
alert_timestamp         datetime64[ns]
anomaly_score                   object
alert_type                      object
risk_level                      object
investigation_status            object
analyst_action                  object
dtype: object

15. First 5 Cleaned Records:
     alert_id transaction_id alert_timestamp anomaly_score         alert_type  \
0  ALRT000001     TXN0004029      2025-02-24         0.194  Multiple Failures
1  ALRT000002     TXN0006211      2026-01-16         0.084   Unusual Location
2  ALRT000003     TXN0005346      2026-06-27         0.862   Unusual Location
3  ALRT000004     TXN0005366      2026-06-14         0.248   Unusual Location
4  ALRT000005     TXN0002162      2025-11-06         0.164   Unusual Location

  risk_level investigation_status    analyst_action
0        Low                  New          Escalate
1        Low         Under Review          Escalate
2   Critical         Under Review  Contact Customer
3        Low         Under Review         No Action
4        Low              Cleared         No Action

========== CHECK COMPLETED ==========